name: drupal-contributions
recipe: drupal9
config:
  webroot: web
  xdebug: 'debug'
services:
  appserver:
    build_as_root:
      # Note that you will want to use the script for the major version of node you want to install
      # See: https://github.com/nodesource/distributions#debian-and-ubuntu-based-distributions
      - apt-get update
      - apt-get install -y ca-certificates curl gnupg
      - curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
      - NODE_MAJOR=16 echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list
      - apt-get update
      - apt-get install nodejs -y
    run:
      - cd /app/web && composer require drush/drush palantirnet/drupal-rector && composer install
      - mkdir -p private/browsertest_output
      - yarn install --non-interactive --cwd /app/web/core
    overrides:
      environment:
        SIMPLETEST_BASE_URL: "https://drupal-contributions.lndo.site/"
        SIMPLETEST_DB: "sqlite://localhost/tmp/db.sqlite"
        BROWSERTEST_OUTPUT_DIRECTORY: '/app/web/sites/simpletest/browser_output'
        BROWSERTEST_OUTPUT_BASE_URL: 'https://drupal-contributions.lndo.site'
        MINK_DRIVER_ARGS_WEBDRIVER: '["chrome", {"browserName":"chrome","chromeOptions":{"args":["--disable-gpu","--headless", "--no-sandbox"]}}, "http://chrome:9515"]'
        # Nightwatch
        DRUPAL_TEST_BASE_URL: 'http://appserver'
        DRUPAL_TEST_DB_URL: 'mysql://drupal9:drupal9@database:3306/drupal9'
        DRUPAL_TEST_WEBDRIVER_HOSTNAME: chrome
        DRUPAL_TEST_WEBDRIVER_PORT: 9515
        DRUPAL_TEST_CHROMEDRIVER_AUTOSTART: 'false'
        DRUPAL_TEST_WEBDRIVER_CHROME_ARGS: "--disable-gpu --headless --no-sandbox"
        DRUPAL_NIGHTWATCH_OUTPUT: reports/nightwatch
        DRUPAL_NIGHTWATCH_IGNORE_DIRECTORIES: node_modules,vendor,.*,sites/*/files,sites/*/private,sites/simpletest
  chrome:
    type: compose
    app_mount: false
    services:
      image: drupalci/webdriver-chromedriver:production
      command: chromedriver --log-path=/tmp/chromedriver.log --allowed-origins=* --verbose --whitelisted-ips=

tooling:
  drush:
    service: appserver
    cmd:
      web/vendor/drush/drush/drush --root=/app/web --uri=https://drupal-contributions.lndo.site
  core-check:
    service: appserver
    cmd:
      - appserver: php /app/scripts/core-check.php
  create-patch:
    service: appserver
    description: Creat a patch from your committed changes on your branch.
    cmd:
      - appserver: php /app/scripts/patch-helpers.php --create-patch
  get-drupal:
    service: appserver
    description: Fetch a fresh copy of Drupal
    cmd:
      - rm -rfv web/
      - php /app/scripts/get-drupal.php
  nightwatch:
    service: appserver
    description: Run Nightwatch.js
    cmd: yarn test:nightwatch
    dir: /app/web/core
  patch:
    service: appserver
    description: Get a patch from a Drupal project issue queue
    cmd:
      - appserver: php /app/scripts/patch-helpers.php
    options:
      url:
        describe: The url of the patch from the issue queue
  phpcbf:
    service: appserver
    cmd: /app/vendor/bin/phpcbf --standard=Drupal,DrupalPractice
  phpcs:
    service: appserver
    cmd: /app/vendor/bin/phpcs --standard=Drupal,DrupalPractice
  phpstan:
    service: appserver
    cmd: vendor/bin/phpstan analyze --configuration="core/phpstan.neon.dist"
  phpunit:
    service: appserver
    user: www-data
    cmd:
      - appserver: php /app/web/vendor/bin/phpunit -c /app/phpunit.xml
  rector:
    service: appserver
    cmd:
      - web/vendor/bin/rector
  revert:
    service: appserver
    description: Apply a patch from a Drupal project issue queue
    cmd:
      - appserver: php /app/scripts/patch-helpers.php --revert
    patch:
      describe: The name of the patch to revert; i.e. DESCRIPTION-XXXXXXX-YY.patch
  si:
    service: appserver
    description: Install Drupal
    cmd:
      - appserver: /app/scripts/site-install.sh
  xdebug-on:
    service: appserver
    description: Enable xdebug for Apache.
    cmd: rm -f /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && docker-php-ext-enable xdebug && /etc/init.d/apache2 reload && echo "Xdebug enabled"
    user: root

  xdebug-off:
    service: appserver
    description: Disable xdebug for Apache.
    cmd: rm -f /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && /etc/init.d/apache2 reload && echo "Xdebug disabled"
    user: root

events:
  post-start:
    - if [ ! -d web ] ; then php /app/scripts/get-drupal.php ; fi
  post-destroy:
    - chmod 777 -R web/sites/default
    - rm -rfv web
  post-rebuild:
    - appserver: /app/scripts/rebuild.sh
## I moved this to a manual command.
#  pre-rebuild:
#    - rm -rfv web
#    - appserver: php /app/scripts/get-drupal.php
